export const Role = {
  ADMIN: 'ADMIN',
  OWNER: 'OWNER',
  MEMBER: 'MEMBER',
  GUEST: 'GUEST',
};

export const AccountStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BANNED: 'BANNED',
};

export const DeviceType = {
  LIGHT: 'LIGHT',
  AC: 'AC',
  DOOR: 'DOOR',
  SMART_PLUG: 'SMART_PLUG',
  TEMPERATURE_SENSOR: 'TEMPERATURE_SENSOR',
  HUMIDITY_SENSOR: 'HUMIDITY_SENSOR',
  MOTION_SENSOR: 'MOTION_SENSOR',
  CAMERA: 'CAMERA',
};
